version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/organizationDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
